#执行交易进化命令后执行的命令
tradeEvoCommand:
  - "money take %player% 500"
#执行等级进化命令后执行的命令
evoCommand:
  - "money take %player% 3000"
#使用rpe heal命令后执行的自定义命令
Heal:
  command:
    - "msg %player% 治疗成功了！"

#有关停止战斗的命令和对应的信息 其中enable是开关 设置为false即可关闭
stopBattle:
  enable: true
  command:
    - "/tz"
  message: "&e已为您停止对战！"
#战斗后自动治疗
BattleEndToHeal:
  enable: true
  #战斗后自动治疗需要的权限
  permission: "pokemon.heal"
  #战斗后执行的自定义指令
  command:
    - "msg %player% 治疗成功了！"
#宝可梦展示一只精灵的格式
ShowPokemonMessage:
  #自定义展示宝可梦信息格式
  playerMessage: "&e%player%&f展示了精灵:"
  pokemonMessage: "[&b%pokemon%&f]"
#宝可梦展示全部精灵的格式
ShowAllPokemonMessage:
  #自定义展示宝可梦信息格式 这个pokemonMessage默认六个 如果你希望有间隔 可以这样"[&b%pokemon%&f] "加个空格
  playerMessage: "&e%player%&f展示了全队精灵:"
  pokemonMessage: "[&b%pokemon%&f]"

rgp:
  #执行rgp命令后 执行以下命令，但是如果list:xxx的话 则执行list列表里的命令 不执行以下的命令 其他rsp rbp同理
  commands:
    - "msg %player% 恭喜获得一只%pokemon%"
  #黑名单列表
  blacklist: "blacklist"
  list:
    # rgp SwagRee list:test 就是获取test列表的宝可梦 如下 然后test读取pokelist example.yml里的东西
    test:
      #pokemonList读取的是配置文件中pokelist中的example.yml文件的宝可梦配置
      pokemonList: "example"
      command:
        - "broadcast 恭喜%player%获得%pokemon%"
rsp:
  commands:
    - "msg %player% 生成了一只%pokemon%"
  blacklist: "blacklist"
  list:
    # rsp SwagRee list:test 就是获取test列表的宝可梦 如下 然后test读取pokelist example.yml里的东西
    test:
      #pokemonList读取的是配置文件中pokelist中的example.yml文件的宝可梦配置
      pokemonList: "example"
      command:
        - "broadcast 恭喜%player%获得%pokemon%"#gui的pc显示的部分
rbp:
  flagCommands:
    #这里的test是标签名 例如/rbp SwagRee 喵喵 flag:test 就是对战拥有test标签的喵喵
    test:
      # 对战成功执行的命令
      success:
        - "say &e%player%成功击败宝可梦，获得丰厚大奖"
      fail:
        # 对战失败执行的命令
        - "say &e%player%你失败了"
  commands:
    - "msg %player% 对战了一只%pokemon%"
  blacklist: "blacklist"
  #列表能随机的宝可梦
  list:
    # rsp SwagRee list:test 就是获取test列表的宝可梦 如下 然后test读取pokelist example.yml里的东西
    test:
      #pokemonList读取的是配置文件中pokelist中的example.yml文件的宝可梦配置
      pokemonList: "example"
      command:
        - "msg %player% 你对战了%pokemon%"

#gui的pc显示的部分
lore:
  - '&f'
  - '&a ▶ &b等级: &f%LEVEL% '
  - '&a ▶ &b个体信息'
  - '&f  ▪ &a血量:&f %IVS_HP% &a攻击:&f %IVS_Attack%'
  - '&f  ▪ &a速度:&f %IVS_Speed% &a防御:&f %IVS_Defence%'
  - '&f  ▪ &a特攻:&f %IVS_SpecialAttack% &a特防:&f %IVS_SpecialDefence%'
  - '&a ▶ &b努力值信息'
  - '&f  ▪ &a血量:&f %EVS_HP% &a攻击:&f %EVS_Attack%'
  - '&f  ▪ &a速度:&f %EVS_Speed% &a防御:&f %EVS_Defence%'
  - '&f  ▪ &a特攻:&f %EVS_SpecialAttack% &a特防:&f %EVS_SpecialDefence%'
  - '&a ▶ &b基础信息:'
  - '&f  ▪ &a闪光: &f%Shiny%'
  - '&f  ▪ &a特性: &f%Ability%'
  - '&f  ▪ &a性格: &f%Nature%'
  - '&f  ▪ &a体型: &f%Growth%'
  - '&f  ▪ &a性别: &f%Gender%'
  - '&f  ▪ &a绑定: &f%BIND%'
  - '&f  ▪ &a昵称: &f%Nick_Name%'

